# Generated by Django 4.2.7 on 2023-11-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=130)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('message', models.TextField()),
            ],
        ),
    ]
