# Generated by Django 4.2.7 on 2023-11-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companywebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='datetime',
            field=models.CharField(max_length=120),
        ),
    ]
